[tool.poetry]
name = "sprint-simulator"
version = "0.1.0"
description = ""
authors = ["Alexander Pronin <a.pronin@m3ii.tech>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
